/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPayrollRouteImport } from './routes/_app.payroll'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppInkRouteImport } from './routes/_app.ink'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInkRoute = AppInkRouteImport.update({
  id: '/ink',
  path: '/ink',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/unlock': typeof UnlockRoute
  '/attendance': typeof AppAttendanceRoute
  '/clients': typeof AppClientsRoute
  '/employees': typeof AppEmployeesRoute
  '/ink': typeof AppInkRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/payroll': typeof AppPayrollRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/unlock': typeof UnlockRoute
  '/attendance': typeof AppAttendanceRoute
  '/clients': typeof AppClientsRoute
  '/employees': typeof AppEmployeesRoute
  '/ink': typeof AppInkRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/payroll': typeof AppPayrollRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/unlock': typeof UnlockRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/ink': typeof AppInkRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/unlock'
    | '/attendance'
    | '/clients'
    | '/employees'
    | '/ink'
    | '/inventory'
    | '/invoices'
    | '/payroll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/unlock'
    | '/attendance'
    | '/clients'
    | '/employees'
    | '/ink'
    | '/inventory'
    | '/invoices'
    | '/payroll'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/unlock'
    | '/_app/attendance'
    | '/_app/clients'
    | '/_app/employees'
    | '/_app/ink'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/payroll'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ink': {
      id: '/_app/ink'
      path: '/ink'
      fullPath: '/ink'
      preLoaderRoute: typeof AppInkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppClientsRoute: typeof AppClientsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInkRoute: typeof AppInkRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppClientsRoute: AppClientsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInkRoute: AppInkRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
